### ISSUE TITLE
fix agmb-docker

### ISSUE THREAD

**Issue by wielandbrendel** [bethgelab/docker-deeplearning#10]
We want to replace our current bash-script agmb-docker with a python-based script that:

- [x] sets the username & userID
- [x] chooses random ports for the jupyter notebook & SSH connection
- [x] adds the home-directory (or the whole bethge-folder if script detects it is running within CIN)
- [x] displays some helper information

**Comment by jonasrauber** [comment]
the random ports should be high enough; I still see some people in the lab using ports below 1024; theoretically, we should even use ports above 49151 [https://en.wikipedia.org/wiki/Registered_port]()
