### ISSUE TITLE
TensorFlow release candidates

### ISSUE THREAD

**Issue by jonasrauber** [bethgelab/docker-deeplearning#8]
I am wondering whether we should explicitly specify the TensorFlow version number and to install release canidates as the default.

**Comment by wielandbrendel** [comment]
Why not take the latest stable version available with pip install?

**Comment by jonasrauber** [comment]
depends on how we plan to upgrade to newer versions later; usually the recommended way is to specify version numbers in Dockerfiles explicitly (at least for those packages for which the version matters), in order to enforce a rebuild of the specific command when a new version is released (otherwise, we might not even have the latest stable, because the command doesn't change and Docker caches it); on DockerHub it wouldn't matter because it doesn't cache the result, but then you would need to manually trigger a rebuild; it's `pip install` either way

**Comment by aecker** [comment]
I think it makes sense to specify the version number. If someone always wants the latest, they can simply add that command to their own container on top.

**Comment by wielandbrendel** [comment]
Specifying the version or just using the latest stable build of Tensorflow won't change the update frequency of that package: I'd expect that we update anyways whenever a new (stable) version of TF is coming out. If we add a version to TF, then we should do so for basically all packages, which could possibly increase the stability of the image (but increases maintenance!).

**Comment by jonasrauber** [comment]
I agree with @aecker.
@wielandbrendel I am not sure if it's really necessary to specify the version number for every package, just because we specify it for TensorFlow. But even if we did that, I am not convinced that it really increases maintenance – as you say yourself, it increases stability and thus might actually reduce maintenance.

**Comment by wielandbrendel** [comment]
I still don't see a convincing reason against just installing the latest stable build of TF (which is still 0.12.1, not the 1.0.0RC) - we are going to install that version anyways. But if you two are set on adding a version then go ahead with it.

**Comment by jonasrauber** [comment]
I am not set on it, but I'd prefer to specify the version number explicitly.

Regarding the 0.12.1 stable vs. 1.0.0rc, I am not sure, but I wanted to bring it up, because then, one could always be sure that whoever is using the new image is also using a TensorFlow version ≥ 1.0.0. There are so many breaking changes and incompatibilities between 0.12 and 1.0 that it would just be nice if one won't have to wonder whether someone's using a pre-1.0 release or not while debugging their code, as long as one knows they are using the new images.
Personally, I often upgrade TensorFlow to the latest beta version in my own images anyway, so I can live with the 0.12.1 being installed in the bethgelab images.  But I think it would make life easier to have some consistency regarding major version numbers in the lab, which could be achieved if the new image always implies Python 3.6 and TensorFlow 1.0.0 (even if it's RC). Assuming the 1.0.0 final will be released during the dev summit, the latest, it wouldn't be a RC anyway when people upgrade to the new containers.

**Comment by jonasrauber** [comment]
Let's resolve this by using the 1.0.0 final once it's out. Should be soon.

**Comment by wielandbrendel** [comment]
I think this can be closed as TF API is now much more stable then before 1.0.0.
